--- #YAML:1.0
name:                IO-Socket-Multicast
version:             1.11
abstract:            Send and receive multicast messages
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Interface:                 0.94
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
